### ISSUE TITLE
Ability to export 1:1 pixel art

### ISSUE THREAD

**Issue by alexgleason** [donatj/Circle-Generator#5]
Hi, thanks for working on this! This tool is soooo close to what I need constantly while making pixel art, but the exported PNGs seem obviously designed as a reference for Minecraft players to individually place blocks.

What I really need is the ability to export an actual size filled pixel art circle. I'm wondering if it's possible to do this without much modification.

I've been maintaining this "shapes" file for my pixel art projects:

![shapes](https://user-images.githubusercontent.com/3639540/54996979-16103280-4fa1-11e9-81af-ebfa6731759b.png)

and I'm dreading the idea that I might have to draw all these different circle files from scratch any time I need a new size. :sweat_smile: 

This tool would be a tremendous help for pixel artists if it could export the actual 1:1 image. Thanks for your time.

**Comment by donatj** [comment]
It would actually be more involved than one would think. 

The current render pipeline is all vector based, output as SVG. When it comes time to output a PNG I just ask the browser politely to convert it to PNG for me. I don't have much direct control over how it does that.

Getting SVG to map to single pixels would be reasonably complicated. I could also build a separate render process that outputs the single pixels, but that would complicate the script a fair bit.

I'm curious the necessity? Doesn't basically every drawing tool including MSPaint create filled circles?

I'm on a Mac, but playing with https://jspaint.app/#local:b013ff4df7399 it seems to do the job as well.

![image](https://user-images.githubusercontent.com/133747/55018916-d73ea480-4fc1-11e9-8070-8050d0bb7935.png)

**Comment by alexgleason** [comment]
Thanks for the suggestion! I was using Krita to draw circles, but getting jagged ones when using a pixel art brush. :confused:

I tried in AESPRITE instead and that seems to do the trick. Perhaps I was over-complicating this. :sweat_smile:
